---

- name: lrdq
  hosts: dev
  remote_user: vagrant

  roles:
    - role: gantsign.oh-my-zsh
      users:
        - username: vagrant
    - role: geerlingguy.nodejs
      nodejs_version: "10.x"
    - role: yarn
      app_dir: /var/www/lrdq.local
    - mysql
    - role: geerlingguy.nodejs
      nodejs_version: "10.x"
    - role: yarn
      app_dir: /var/www/lrdq.local
    - role: php7_1
      php_dev: yes
    - role: apache2
      become: yes
      apache_vhosts:
        # Additional optional properties: 'serveradmin, serveralias, extra_parameters'.
        - servername: "lrdq.local"
          documentroot: "/var/www/lrdq.local/public"
    - common
    - role: symfony4
      app_dir: /var/www/lrdq.local

...
