- name: install required packages
  apt: name="{{ item }}" state="latest" update_cache=yes
  become: yes
  tags: php
  with_items: "{{ required_packages }}"

- name: get php 7.1 repo
  become: yes
  shell: wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg

- name: get php 7.1 repo
  become: yes
  shell:  sh -c 'echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/php.list'

- name: get php 7.1 repo
  become: yes
  shell: apt-get update

- name: Install php7.1
  apt: name="{{ item }}" state="latest" update_cache=yes
  become: yes
  tags: php
  with_items: "{{ php_7_1_packages }}"

- name: Install php7.1 dev
  apt: name="{{ item }}" state="latest" update_cache=yes
  become: yes
  tags: php
  with_items: "{{ php_7_1_packages_dev }}"
  when: php_dev

- name: Conf php7.1 xdebug 1
  become: yes
  lineinfile: dest=/etc/php/7.1/fpm/conf.d/20-xdebug.ini line="xdebug.remote_enable=true"
  when: php_dev

- name: Conf php7.1 xdebug 2
  become: yes
  lineinfile: dest=/etc/php/7.1/fpm/conf.d/20-xdebug.ini line="xdebug.remote_port=9000"
  when: php_dev
  
- name: Conf php7.1 xdebug 3
  become: yes
  lineinfile: dest=/etc/php/7.1/fpm/conf.d/20-xdebug.ini line="xdebug.remote_host=10.0.0.1"
  when: php_dev
