php_7_1_packages:
    - php7.1
    - php7.1-common
    - php7.1-cli
    - php7.1-intl
    - php7.1-curl
    - php7.1-fpm
    - php7.1-gd
    - php7.1-mysql
    - php7.1-mcrypt
    - php7.1-xml
    - php7.1-xsl
    - php7.1-zip
    - libapache2-mod-php7.1
    - php7.1-mbstring

required_packages:
    - apt-transport-https 
    - lsb-release 
    - ca-certificates

php_dev: no
php_7_1_packages_dev:
    - php7.1-xdebug

composer_path: /usr/local/bin/composer
composer_keep_updated: false
composer_version: ''

# The directory where global packages will be installed.
composer_home_path: '~/.composer'
composer_home_owner: root
composer_home_group: root

# A list of packages to install globally. See commented examples below for
# usage; the 'release' is optional, and defaults to '@stable'.
composer_global_packages: []
  # - { name: phpunit/phpunit, release: "4.7.x" }
  # - { name: phpunit/phpunit, release: "@stable" }

composer_add_to_path: true

# GitHub OAuth token (used to help overcome API rate limits).
composer_github_oauth_token: ''
